---
cache:
  '1':
    DC: 1
    DP: 2414
    zi: 2420
  '2':
    DC: 1
    DP: 6209
    zi: 6211
  '3':
    DC: 1
    DP: 5798
    zi: 5797
  '4':
    DC: 1
    DP: 3603
    zi: 3604
  '5':
    DC: 1
    DP: 1969
    zi: 1969
  '6':
    DC: 1
    DP: 2908
    zi: 2911
  '7':
    DC: 1
    DP: 5012
    zi: 5010
  '8':
    DC: 1
    DP: 4330
    zi: 4334
timestamp: 2020-05-21 11:58:56
